// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiTA-w3tWJTuPLkLQpwJ6vXly-houEQU',
    appId: '1:1068891917532:web:6c9e86690edd787342f819',
    messagingSenderId: '1068891917532',
    projectId: 'first-app-eea9d',
    authDomain: 'first-app-eea9d.firebaseapp.com',
    databaseURL: 'https://first-app-eea9d-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-eea9d.appspot.com',
    measurementId: 'G-7TDBWR17N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt8PtCoqG18QnT70dzFvr58wsZHZ6NyW4',
    appId: '1:1068891917532:android:3ca5c1741139aa3542f819',
    messagingSenderId: '1068891917532',
    projectId: 'first-app-eea9d',
    databaseURL: 'https://first-app-eea9d-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-eea9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6VnuY7KFbIx9Nq4yLGXVz4BK8V_fDTU',
    appId: '1:1068891917532:ios:55f07e65a40b61b942f819',
    messagingSenderId: '1068891917532',
    projectId: 'first-app-eea9d',
    databaseURL: 'https://first-app-eea9d-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-eea9d.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6VnuY7KFbIx9Nq4yLGXVz4BK8V_fDTU',
    appId: '1:1068891917532:ios:7d74234ba0d6ec0c42f819',
    messagingSenderId: '1068891917532',
    projectId: 'first-app-eea9d',
    databaseURL: 'https://first-app-eea9d-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-eea9d.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
